#!/usr/bin/env python3
"""Fix single-brace syntax in state list.html templates.

Files generated by gen_state_scaffolding.py used:
  { with .Params.cover }<img ...>{ end }
instead of Hugo's required:
  {{ with .Params.cover }}<img ...>{{ end }}
"""

import os
import glob

LAYOUTS = "/opt/data/civic-data-explainers/hugo-site/layouts"

fixed = 0
for path in glob.glob(f"{LAYOUTS}/*/list.html"):
    with open(path) as f:
        content = f.read()

    if "{ with" in content or "{ end }" in content:
        new_content = content.replace("{ with", "{{ with").replace("{ end }", "{{ end }}")
        if new_content != content:
            with open(path, "w") as f:
                f.write(new_content)
            fixed += 1
            print(f"Fixed: {os.path.relpath(path, LAYOUTS)}")

print(f"\nTotal fixed: {fixed}")
